{
    "issues": [
        {
            "expand": "renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations,customfield_10010.requestTypePractice",
            "id": "10002",
            "self": "https://basenji.atlassian.net/rest/api/2/issue/10002",
            "key": "KAL-3",
            "fields": {
                "statuscategorychangedate": "2023-08-12T12:48:05.762-0500",
                "issuetype": {
                    "self": "https://basenji.atlassian.net/rest/api/2/issuetype/10001",
                    "id": "10001",
                    "description": "Functionality or a feature expressed as a user goal.",
                    "iconUrl": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium",
                    "name": "Story",
                    "subtask": False,
                    "avatarId": 10315,
                    "hierarchyLevel": 0,
                },
                "timespent": None,
                "customfield_10030": None,
                "customfield_10031": 1.0,
                "project": {
                    "self": "https://basenji.atlassian.net/rest/api/2/project/10001",
                    "id": "10001",
                    "key": "KAL",
                    "name": "Kalupoh",
                    "projectTypeKey": "software",
                    "simplified": False,
                    "avatarUrls": {
                        "48x48": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10406",
                        "24x24": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10406?size=small",
                        "16x16": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10406?size=xsmall",
                        "32x32": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10406?size=medium",
                    },
                },
                "fixVersions": [],
                "customfield_10034": None,
                "statusCategory": {
                    "self": "https://basenji.atlassian.net/rest/api/2/statuscategory/2",
                    "id": 2,
                    "key": "new",
                    "colorName": "blue-gray",
                    "name": "To Do",
                },
                "aggregatetimespent": None,
                "resolution": None,
                "customfield_10035": None,
                "customfield_10036": None,
                "customfield_10037": None,
                "customfield_10027": None,
                "customfield_10028": None,
                "customfield_10029": None,
                "resolutiondate": None,
                "workratio": -1,
                "lastViewed": None,
                "watches": {
                    "self": "https://basenji.atlassian.net/rest/api/2/issue/KAL-3/watchers",
                    "watchCount": 1,
                    "isWatching": True,
                },
                "created": "2023-08-12T12:48:05.237-0500",
                "customfield_10020": [
                    {
                        "id": 1,
                        "name": "KAL Sprint 1",
                        "state": "active",
                        "boardId": 2,
                        "goal": "",
                        "startDate": "2023-08-05T03:49:45.628Z",
                        "endDate": "2023-08-19T03:49:00.000Z",
                    }
                ],
                "customfield_10021": None,
                "customfield_10022": None,
                "customfield_10023": None,
                "priority": {
                    "self": "https://basenji.atlassian.net/rest/api/2/priority/3",
                    "iconUrl": "https://basenji.atlassian.net/images/icons/priorities/medium_new.svg",
                    "name": "Medium",
                    "id": "3",
                },
                "customfield_10024": None,
                "customfield_10025": None,
                "labels": [],
                "customfield_10016": None,
                "customfield_10017": None,
                "customfield_10018": {
                    "hasEpicLinkFieldDependency": False,
                    "showField": False,
                    "nonEditableReason": {
                        "reason": "PLUGIN_LICENSE_ERROR",
                        "message": "The Parent Link is only available to Jira Premium users.",
                    },
                },
                "customfield_10019": "0|hzzzzz:",
                "timeestimate": None,
                "aggregatetimeoriginalestimate": None,
                "versions": [],
                "issuelinks": [],
                "assignee": None,
                "updated": "2023-08-16T13:39:11.753-0500",
                "status": {
                    "self": "https://basenji.atlassian.net/rest/api/2/status/10000",
                    "description": "",
                    "iconUrl": "https://basenji.atlassian.net/",
                    "name": "To Do",
                    "id": "10000",
                    "statusCategory": {
                        "self": "https://basenji.atlassian.net/rest/api/2/statuscategory/2",
                        "id": 2,
                        "key": "new",
                        "colorName": "blue-gray",
                        "name": "To Do",
                    },
                },
                "components": [],
                "timeoriginalestimate": None,
                "description": "Esta es una prueba dela interacción de Jira con bitbucket",
                "customfield_10010": None,
                "customfield_10014": None,
                "timetracking": {},
                "customfield_10015": None,
                "customfield_10005": None,
                "customfield_10006": None,
                "security": None,
                "customfield_10007": None,
                "customfield_10008": None,
                "customfield_10009": None,
                "aggregatetimeestimate": None,
                "attachment": [],
                "summary": "Create User",
                "creator": {
                    "self": "https://basenji.atlassian.net/rest/api/2/user?accountId=63c08bd327c8920a5c02dbd2",
                    "accountId": "63c08bd327c8920a5c02dbd2",
                    "emailAddress": "hector.viveros.58@gmail.com",
                    "avatarUrls": {
                        "48x48": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "24x24": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "16x16": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "32x32": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                    },
                    "displayName": "Hector Viveros",
                    "active": True,
                    "timeZone": "America/Chicago",
                    "accountType": "atlassian",
                },
                "subtasks": [],
                "customfield_10040": None,
                "reporter": {
                    "self": "https://basenji.atlassian.net/rest/api/2/user?accountId=63c08bd327c8920a5c02dbd2",
                    "accountId": "63c08bd327c8920a5c02dbd2",
                    "emailAddress": "hector.viveros.58@gmail.com",
                    "avatarUrls": {
                        "48x48": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "24x24": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "16x16": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "32x32": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                    },
                    "displayName": "Hector Viveros",
                    "active": True,
                    "timeZone": "America/Chicago",
                    "accountType": "atlassian",
                },
                "aggregateprogress": {"progress": 0, "total": 0},
                "customfield_10000": '{repository={count=1, dataType=repository}, json={"cachedValue":{"errors":[],"summary":{"repository":{"overall":{"count":1,"lastUpdated":"2023-08-23T17:07:19.000-0500","dataType":"repository"},"byInstanceType":{"bitbucket":{"count":1,"name":"Bitbucket Cloud"}}}}},"isStale":true}}',
                "customfield_10001": None,
                "customfield_10002": [],
                "customfield_10003": None,
                "customfield_10004": None,
                "customfield_10039": None,
                "environment": None,
                "duedate": None,
                "progress": {"progress": 0, "total": 0},
                "votes": {
                    "self": "https://basenji.atlassian.net/rest/api/2/issue/KAL-3/votes",
                    "votes": 0,
                    "hasVoted": False,
                },
                "comment": {
                    "comments": [],
                    "self": "https://basenji.atlassian.net/rest/api/2/issue/10002/comment",
                    "maxResults": 0,
                    "total": 0,
                    "startAt": 0,
                },
                "worklog": {"startAt": 0, "maxResults": 20, "total": 0, "worklogs": []},
            },
        },
        
        {
            "expand": "renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations,customfield_10010.requestTypePractice",
            "id": "10001",
            "self": "https://basenji.atlassian.net/rest/api/2/issue/10001",
            "key": "KAL-2",
            "fields": {
                "statuscategorychangedate": "2023-08-04T22:46:15.952-0500",
                "issuetype": {
                    "self": "https://basenji.atlassian.net/rest/api/2/issuetype/10001",
                    "id": "10001",
                    "description": "Functionality or a feature expressed as a user goal.",
                    "iconUrl": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium",
                    "name": "Story",
                    "subtask": False,
                    "avatarId": 10315,
                    "hierarchyLevel": 0,
                },
                "timespent": None,
                "customfield_10030": None,
                "customfield_10031": 8.0,
                "project": {
                    "self": "https://basenji.atlassian.net/rest/api/2/project/10001",
                    "id": "10001",
                    "key": "KAL",
                    "name": "Kalupoh",
                    "projectTypeKey": "software",
                    "simplified": False,
                    "avatarUrls": {
                        "48x48": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10406",
                        "24x24": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10406?size=small",
                        "16x16": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10406?size=xsmall",
                        "32x32": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10406?size=medium",
                    },
                },
                "fixVersions": [],
                "customfield_10034": None,
                "statusCategory": {
                    "self": "https://basenji.atlassian.net/rest/api/2/statuscategory/2",
                    "id": 2,
                    "key": "new",
                    "colorName": "blue-gray",
                    "name": "To Do",
                },
                "aggregatetimespent": None,
                "resolution": None,
                "customfield_10035": None,
                "customfield_10036": None,
                "customfield_10037": None,
                "customfield_10027": None,
                "customfield_10028": None,
                "customfield_10029": None,
                "resolutiondate": None,
                "workratio": -1,
                "lastViewed": "2025-06-08T12:38:49.230-0500",
                "watches": {
                    "self": "https://basenji.atlassian.net/rest/api/2/issue/KAL-2/watchers",
                    "watchCount": 0,
                    "isWatching": False,
                },
                "created": "2023-08-04T22:46:15.321-0500",
                "customfield_10020": [
                    {
                        "id": 1,
                        "name": "KAL Sprint 1",
                        "state": "active",
                        "boardId": 2,
                        "goal": "",
                        "startDate": "2023-08-05T03:49:45.628Z",
                        "endDate": "2023-08-19T03:49:00.000Z",
                    }
                ],
                "customfield_10021": None,
                "customfield_10022": None,
                "customfield_10023": None,
                "priority": {
                    "self": "https://basenji.atlassian.net/rest/api/2/priority/3",
                    "iconUrl": "https://basenji.atlassian.net/images/icons/priorities/medium_new.svg",
                    "name": "Medium",
                    "id": "3",
                },
                "customfield_10024": None,
                "customfield_10025": None,
                "labels": [],
                "customfield_10016": None,
                "customfield_10017": None,
                "customfield_10018": {
                    "hasEpicLinkFieldDependency": False,
                    "showField": False,
                    "nonEditableReason": {
                        "reason": "PLUGIN_LICENSE_ERROR",
                        "message": "The Parent Link is only available to Jira Premium users.",
                    },
                },
                "customfield_10019": "0|hzzzzr:",
                "timeestimate": None,
                "aggregatetimeoriginalestimate": None,
                "versions": [],
                "issuelinks": [],
                "assignee": None,
                "updated": "2023-08-04T22:49:26.282-0500",
                "status": {
                    "self": "https://basenji.atlassian.net/rest/api/2/status/10000",
                    "description": "",
                    "iconUrl": "https://basenji.atlassian.net/",
                    "name": "To Do",
                    "id": "10000",
                    "statusCategory": {
                        "self": "https://basenji.atlassian.net/rest/api/2/statuscategory/2",
                        "id": 2,
                        "key": "new",
                        "colorName": "blue-gray",
                        "name": "To Do",
                    },
                },
                "components": [],
                "timeoriginalestimate": None,
                "description": "As a user, I want to be able to create a ticket",
                "customfield_10010": None,
                "customfield_10014": None,
                "timetracking": {},
                "customfield_10015": None,
                "customfield_10005": None,
                "customfield_10006": None,
                "security": None,
                "customfield_10007": None,
                "customfield_10008": None,
                "customfield_10009": None,
                "aggregatetimeestimate": None,
                "attachment": [],
                "summary": "Create tickets",
                "creator": {
                    "self": "https://basenji.atlassian.net/rest/api/2/user?accountId=63c08bd327c8920a5c02dbd2",
                    "accountId": "63c08bd327c8920a5c02dbd2",
                    "emailAddress": "hector.viveros.58@gmail.com",
                    "avatarUrls": {
                        "48x48": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "24x24": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "16x16": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "32x32": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                    },
                    "displayName": "Hector Viveros",
                    "active": True,
                    "timeZone": "America/Chicago",
                    "accountType": "atlassian",
                },
                "subtasks": [],
                "customfield_10040": None,
                "reporter": {
                    "self": "https://basenji.atlassian.net/rest/api/2/user?accountId=63c08bd327c8920a5c02dbd2",
                    "accountId": "63c08bd327c8920a5c02dbd2",
                    "emailAddress": "hector.viveros.58@gmail.com",
                    "avatarUrls": {
                        "48x48": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "24x24": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "16x16": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "32x32": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                    },
                    "displayName": "Hector Viveros",
                    "active": True,
                    "timeZone": "America/Chicago",
                    "accountType": "atlassian",
                },
                "aggregateprogress": {"progress": 0, "total": 0},
                "customfield_10000": "{}",
                "customfield_10001": None,
                "customfield_10002": [],
                "customfield_10003": None,
                "customfield_10004": None,
                "customfield_10039": None,
                "environment": None,
                "duedate": None,
                "progress": {"progress": 0, "total": 0},
                "votes": {
                    "self": "https://basenji.atlassian.net/rest/api/2/issue/KAL-2/votes",
                    "votes": 0,
                    "hasVoted": False,
                },
                "comment": {
                    "comments": [],
                    "self": "https://basenji.atlassian.net/rest/api/2/issue/10001/comment",
                    "maxResults": 0,
                    "total": 0,
                    "startAt": 0,
                },
                "worklog": {"startAt": 0, "maxResults": 20, "total": 0, "worklogs": []},
            },
        },
        
        {
            "expand": "renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations,customfield_10010.requestTypePractice",
            "id": "10000",
            "self": "https://basenji.atlassian.net/rest/api/2/issue/10000",
            "key": "KAL-1",
            "fields": {
                "statuscategorychangedate": "2023-08-04T23:10:06.166-0500",
                "issuetype": {
                    "self": "https://basenji.atlassian.net/rest/api/2/issuetype/10001",
                    "id": "10001",
                    "description": "Functionality or a feature expressed as a user goal.",
                    "iconUrl": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium",
                    "name": "Story",
                    "subtask": False,
                    "avatarId": 10315,
                    "hierarchyLevel": 0,
                },
                "timespent": None,
                "customfield_10030": None,
                "customfield_10031": 1.5,
                "project": {
                    "self": "https://basenji.atlassian.net/rest/api/2/project/10001",
                    "id": "10001",
                    "key": "KAL",
                    "name": "Kalupoh",
                    "projectTypeKey": "software",
                    "simplified": False,
                    "avatarUrls": {
                        "48x48": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10406",
                        "24x24": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10406?size=small",
                        "16x16": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10406?size=xsmall",
                        "32x32": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10406?size=medium",
                    },
                },
                "fixVersions": [],
                "statusCategory": {
                    "self": "https://basenji.atlassian.net/rest/api/2/statuscategory/4",
                    "id": 4,
                    "key": "indeterminate",
                    "colorName": "yellow",
                    "name": "In Progress",
                },
                "customfield_10034": None,
                "aggregatetimespent": None,
                "resolution": None,
                "customfield_10035": None,
                "customfield_10036": None,
                "customfield_10037": None,
                "customfield_10027": None,
                "customfield_10028": None,
                "customfield_10029": None,
                "resolutiondate": None,
                "workratio": -1,
                "lastViewed": None,
                "watches": {
                    "self": "https://basenji.atlassian.net/rest/api/2/issue/KAL-1/watchers",
                    "watchCount": 0,
                    "isWatching": False,
                },
                "created": "2023-08-04T22:45:37.747-0500",
                "customfield_10020": [
                    {
                        "id": 1,
                        "name": "KAL Sprint 1",
                        "state": "active",
                        "boardId": 2,
                        "goal": "",
                        "startDate": "2023-08-05T03:49:45.628Z",
                        "endDate": "2023-08-19T03:49:00.000Z",
                    }
                ],
                "customfield_10021": None,
                "customfield_10022": None,
                "customfield_10023": None,
                "priority": {
                    "self": "https://basenji.atlassian.net/rest/api/2/priority/2",
                    "iconUrl": "https://basenji.atlassian.net/images/icons/priorities/high_new.svg",
                    "name": "High",
                    "id": "2",
                },
                "customfield_10024": None,
                "customfield_10025": None,
                "labels": ["Etiqueta1", "Label1"],
                "customfield_10016": None,
                "customfield_10017": None,
                "customfield_10018": {
                    "hasEpicLinkFieldDependency": False,
                    "showField": False,
                    "nonEditableReason": {
                        "reason": "PLUGIN_LICENSE_ERROR",
                        "message": "The Parent Link is only available to Jira Premium users.",
                    },
                },
                "customfield_10019": "0|hzzzzj:",
                "timeestimate": None,
                "aggregatetimeoriginalestimate": None,
                "versions": [],
                "issuelinks": [],
                "assignee": {
                    "self": "https://basenji.atlassian.net/rest/api/2/user?accountId=63c08bd327c8920a5c02dbd2",
                    "accountId": "63c08bd327c8920a5c02dbd2",
                    "emailAddress": "hector.viveros.58@gmail.com",
                    "avatarUrls": {
                        "48x48": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "24x24": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "16x16": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "32x32": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                    },
                    "displayName": "Hector Viveros",
                    "active": True,
                    "timeZone": "America/Chicago",
                    "accountType": "atlassian",
                },
                "updated": "2024-03-24T19:35:18.506-0500",
                "status": {
                    "self": "https://basenji.atlassian.net/rest/api/2/status/3",
                    "description": "This issue is being actively worked on at the moment by the assignee.",
                    "iconUrl": "https://basenji.atlassian.net/images/icons/statuses/inprogress.png",
                    "name": "In Progress",
                    "id": "3",
                    "statusCategory": {
                        "self": "https://basenji.atlassian.net/rest/api/2/statuscategory/4",
                        "id": 4,
                        "key": "indeterminate",
                        "colorName": "yellow",
                        "name": "In Progress",
                    },
                },
                "components": [],
                "timeoriginalestimate": None,
                "description": "Esta es la primera historia de prueba para este proyecto",
                "customfield_10010": None,
                "customfield_10014": None,
                "timetracking": {},
                "customfield_10015": None,
                "customfield_10005": None,
                "customfield_10006": None,
                "security": None,
                "customfield_10007": None,
                "customfield_10008": None,
                "customfield_10009": None,
                "aggregatetimeestimate": None,
                "attachment": [],
                "summary": "Create Projects",
                "creator": {
                    "self": "https://basenji.atlassian.net/rest/api/2/user?accountId=63c08bd327c8920a5c02dbd2",
                    "accountId": "63c08bd327c8920a5c02dbd2",
                    "emailAddress": "hector.viveros.58@gmail.com",
                    "avatarUrls": {
                        "48x48": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "24x24": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "16x16": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "32x32": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                    },
                    "displayName": "Hector Viveros",
                    "active": True,
                    "timeZone": "America/Chicago",
                    "accountType": "atlassian",
                },
                "subtasks": [],
                "customfield_10040": None,
                "reporter": {
                    "self": "https://basenji.atlassian.net/rest/api/2/user?accountId=63c08bd327c8920a5c02dbd2",
                    "accountId": "63c08bd327c8920a5c02dbd2",
                    "emailAddress": "hector.viveros.58@gmail.com",
                    "avatarUrls": {
                        "48x48": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "24x24": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "16x16": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "32x32": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                    },
                    "displayName": "Hector Viveros",
                    "active": True,
                    "timeZone": "America/Chicago",
                    "accountType": "atlassian",
                },
                "aggregateprogress": {"progress": 0, "total": 0},
                "customfield_10000": "{}",
                "customfield_10001": None,
                "customfield_10002": [],
                "customfield_10003": None,
                "customfield_10004": None,
                "customfield_10039": None,
                "environment": None,
                "duedate": None,
                "progress": {"progress": 0, "total": 0},
                "comment": {
                    "comments": [],
                    "self": "https://basenji.atlassian.net/rest/api/2/issue/10000/comment",
                    "maxResults": 0,
                    "total": 0,
                    "startAt": 0,
                },
                "votes": {
                    "self": "https://basenji.atlassian.net/rest/api/2/issue/KAL-1/votes",
                    "votes": 0,
                    "hasVoted": False,
                },
                "worklog": {"startAt": 0, "maxResults": 20, "total": 0, "worklogs": []},
            },
        },
    ]
}
