{
    "issues": [
        {
            "expand": "renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations,customfield_10010.requestTypePractice",
            "id": "10003",
            "self": "https://basenji.atlassian.net/rest/api/2/issue/10003",
            "key": "AM-1",
            "fields": {
                "statuscategorychangedate": "2024-05-03T14:02:38.895-0500",
                "issuetype": {
                    "self": "https://basenji.atlassian.net/rest/api/2/issuetype/10001",
                    "id": "10001",
                    "description": "Functionality or a feature expressed as a user goal.",
                    "iconUrl": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium",
                    "name": "Story",
                    "subtask": False,
                    "avatarId": 10315,
                    "hierarchyLevel": 0,
                },
                "timespent": None,
                "customfield_10030": None,
                "project": {
                    "self": "https://basenji.atlassian.net/rest/api/2/project/10002",
                    "id": "10002",
                    "key": "AM",
                    "name": "Agile Metrics",
                    "projectTypeKey": "software",
                    "simplified": False,
                    "avatarUrls": {
                        "48x48": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10414",
                        "24x24": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10414?size=small",
                        "16x16": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10414?size=xsmall",
                        "32x32": "https://basenji.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10414?size=medium",
                    },
                },
                "customfield_10031": None,
                "fixVersions": [],
                "customfield_10034": None,
                "statusCategory": {
                    "self": "https://basenji.atlassian.net/rest/api/2/statuscategory/2",
                    "id": 2,
                    "key": "new",
                    "colorName": "blue-gray",
                    "name": "To Do",
                },
                "aggregatetimespent": None,
                "resolution": None,
                "customfield_10035": None,
                "customfield_10036": None,
                "customfield_10037": None,
                "customfield_10027": None,
                "customfield_10028": None,
                "customfield_10029": None,
                "resolutiondate": None,
                "workratio": -1,
                "lastViewed": "2025-06-08T12:36:02.896-0500",
                "watches": {
                    "self": "https://basenji.atlassian.net/rest/api/2/issue/AM-1/watchers",
                    "watchCount": 1,
                    "isWatching": True,
                },
                "created": "2024-04-18T11:41:26.224-0500",
                "customfield_10020": None,
                "customfield_10021": None,
                "customfield_10022": None,
                "customfield_10023": None,
                "priority": {
                    "self": "https://basenji.atlassian.net/rest/api/2/priority/3",
                    "iconUrl": "https://basenji.atlassian.net/images/icons/priorities/medium_new.svg",
                    "name": "Medium",
                    "id": "3",
                },
                "customfield_10024": None,
                "customfield_10025": None,
                "labels": [],
                "customfield_10016": None,
                "customfield_10017": None,
                "customfield_10018": {
                    "hasEpicLinkFieldDependency": False,
                    "showField": False,
                    "nonEditableReason": {
                        "reason": "PLUGIN_LICENSE_ERROR",
                        "message": "The Parent Link is only available to Jira Premium users.",
                    },
                },
                "customfield_10019": "0|i0001b:",
                "timeestimate": None,
                "aggregatetimeoriginalestimate": None,
                "versions": [],
                "issuelinks": [],
                "assignee": None,
                "updated": "2025-06-07T22:45:20.280-0500",
                "status": {
                    "self": "https://basenji.atlassian.net/rest/api/2/status/10000",
                    "description": "",
                    "iconUrl": "https://basenji.atlassian.net/",
                    "name": "To Do",
                    "id": "10000",
                    "statusCategory": {
                        "self": "https://basenji.atlassian.net/rest/api/2/statuscategory/2",
                        "id": 2,
                        "key": "new",
                        "colorName": "blue-gray",
                        "name": "To Do",
                    },
                },
                "components": [],
                "timeoriginalestimate": None,
                "description": "Create the scrum boar of the application",
                "customfield_10010": None,
                "customfield_10014": None,
                "timetracking": {},
                "customfield_10015": None,
                "customfield_10005": None,
                "customfield_10006": None,
                "security": None,
                "customfield_10007": None,
                "customfield_10008": None,
                "customfield_10009": None,
                "aggregatetimeestimate": None,
                "attachment": [],
                "summary": "Scrum Board",
                "creator": {
                    "self": "https://basenji.atlassian.net/rest/api/2/user?accountId=63c08bd327c8920a5c02dbd2",
                    "accountId": "63c08bd327c8920a5c02dbd2",
                    "emailAddress": "hector.viveros.58@gmail.com",
                    "avatarUrls": {
                        "48x48": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "24x24": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "16x16": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "32x32": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                    },
                    "displayName": "Hector Viveros",
                    "active": True,
                    "timeZone": "America/Chicago",
                    "accountType": "atlassian",
                },
                "subtasks": [],
                "customfield_10040": None,
                "reporter": {
                    "self": "https://basenji.atlassian.net/rest/api/2/user?accountId=63c08bd327c8920a5c02dbd2",
                    "accountId": "63c08bd327c8920a5c02dbd2",
                    "emailAddress": "hector.viveros.58@gmail.com",
                    "avatarUrls": {
                        "48x48": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "24x24": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "16x16": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                        "32x32": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                    },
                    "displayName": "Hector Viveros",
                    "active": True,
                    "timeZone": "America/Chicago",
                    "accountType": "atlassian",
                },
                "aggregateprogress": {"progress": 0, "total": 0},
                "customfield_10000": "{}",
                "customfield_10001": None,
                "customfield_10002": [],
                "customfield_10003": None,
                "customfield_10004": None,
                "customfield_10039": None,
                "environment": None,
                "duedate": None,
                "progress": {"progress": 0, "total": 0},
                "votes": {
                    "self": "https://basenji.atlassian.net/rest/api/2/issue/AM-1/votes",
                    "votes": 0,
                    "hasVoted": False,
                },
                "comment": {
                    "comments": [
                        {
                            "self": "https://basenji.atlassian.net/rest/api/2/issue/10003/comment/10000",
                            "id": "10000",
                            "author": {
                                "self": "https://basenji.atlassian.net/rest/api/2/user?accountId=63c08bd327c8920a5c02dbd2",
                                "accountId": "63c08bd327c8920a5c02dbd2",
                                "emailAddress": "hector.viveros.58@gmail.com",
                                "avatarUrls": {
                                    "48x48": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                                    "24x24": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                                    "16x16": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                                    "32x32": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                                },
                                "displayName": "Hector Viveros",
                                "active": True,
                                "timeZone": "America/Chicago",
                                "accountType": "atlassian",
                            },
                            "body": "As a scrum master I want to be able to select the board from which sprints will be selected",
                            "updateAuthor": {
                                "self": "https://basenji.atlassian.net/rest/api/2/user?accountId=63c08bd327c8920a5c02dbd2",
                                "accountId": "63c08bd327c8920a5c02dbd2",
                                "emailAddress": "hector.viveros.58@gmail.com",
                                "avatarUrls": {
                                    "48x48": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                                    "24x24": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                                    "16x16": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                                    "32x32": "https://secure.gravatar.com/avatar/b394f5620d3d5cf40bd63c11aad45898?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHV-0.png",
                                },
                                "displayName": "Hector Viveros",
                                "active": True,
                                "timeZone": "America/Chicago",
                                "accountType": "atlassian",
                            },
                            "created": "2024-04-18T13:29:56.666-0500",
                            "updated": "2024-04-18T13:29:56.666-0500",
                            "jsdPublic": True,
                        }
                    ],
                    "self": "https://basenji.atlassian.net/rest/api/2/issue/10003/comment",
                    "maxResults": 1,
                    "total": 1,
                    "startAt": 0,
                },
                "worklog": {"startAt": 0, "maxResults": 20, "total": 0, "worklogs": []},
            },
        }
    ]
}
